import type {DesignInput,Floor,Layout,Room,RoomType} from '../types';
import {uid,round} from '../utils/geometry';
import {validateLayout} from './validation';import {scoreLayout} from './scoring';import {generateCspOrders} from './original-port/cspTree';
function mid(input:DesignInput,k:string){const r=input.areas[k]||{min:6,max:12};return round((r.min+r.max)/2)}
function room(name:string,type:RoomType,floor:number,x:number,y:number,width:number,height:number,targetArea:number):Room{return{id:uid('room'),name,type,floor,x:round(x),y:round(y),width:round(width),height:round(height),targetArea}}
function splitBand(width:number,y:number,h:number,items:{name:string;type:RoomType;area:number}[],floor:number){let x=0;return items.map(it=>{const w=round(Math.max(width*.22,Math.min(width-x,it.area/h)));const r=room(it.name,it.type,floor,x,y,w,h,it.area);x+=w;return r;});}
function generateFloor(input:DesignInput,level:number,variant:number):Floor{const W=input.plot.width,D=input.plot.depth;const rooms:Room[]=[];const stairW=Math.min(2.2,W*.42),stairH=Math.max(3.2,mid(input,'stair')/stairW);const stairY=input.plot.stair==='back'?D-stairH-1:input.plot.stair==='middle'||(input.plot.stair==='auto'&&variant%2)?D*.42:D*.58;const stairX=input.plot.stair==='side'||W<5?0:W-stairW;const add=(r:Room)=>rooms.push(r);
 if(level===1){let y=0;if(input.plot.frontYard){add(room('Sân trước','yard',level,0,0,W,Math.min(2,D*.16),mid(input,'yard')));y+=Math.min(2,D*.16)}if(input.plot.parking==='car') {const h=input.plot.parkingMode==='transverse'&&W>=5.5?3.2:Math.min(5.4,D*.32);add(room('Gara / để xe','garage',level,0,y,W,h,mid(input,'garage')));y+=h}else if(input.plot.parking==='motorbike'){add(room('Sảnh để xe máy','garage',level,0,y,W,2.2,10));y+=2.2}if(input.requirements.living){const h=Math.max(3,mid(input,'living')/W);add(room('Phòng khách','living',level,0,y,W,h,mid(input,'living')));y+=h}add(room('Cầu thang + sảnh','stair',level,stairX,stairY,stairW,stairH,mid(input,'stair')));const kitchenY=Math.max(y,stairY+stairH);if(input.requirements.kitchen)add(room('Bếp + ăn','kitchen',level,0,kitchenY,W,Math.max(3,Math.min(D-kitchenY,mid(input,'kitchen')/W)),mid(input,'kitchen')));if(input.requirements.wcs>0)add(room('WC chung','wc',level,W-1.8,Math.min(D-2.4,stairY+stairH+.2),1.8,2.4,mid(input,'wc')));if(input.plot.backYard||input.plot.void)add(room(input.plot.void?'Giếng trời / sân sau':'Sân sau','void',level,0,D-1.5,W,1.5,mid(input,'void')))}
 else{add(room('Cầu thang + hành lang','stair',level,stairX,stairY,stairW,stairH,mid(input,'stair')));const bedCount=Math.max(0,Math.ceil(input.requirements.bedrooms/Math.max(1,input.plot.floors-1)));const top=splitBand(W,0,D*.42,[{name:level===2&&input.requirements.masterSuite?'Master bedroom':'Phòng ngủ',type:level===2&&input.requirements.masterSuite?'master':'bedroom',area:level===2?mid(input,'master'):mid(input,'bedroom')}],level);rooms.push(...top);if(level===2&&input.requirements.masterSuite)add(room('WC riêng master','master-wc',level,W-1.8,D*.42,1.8,2.3,mid(input,'master-wc')));for(let i=1;i<bedCount;i++)add(room(`Phòng ngủ ${level}.${i}`,'bedroom',level,0,D*.55,W*.55,D*.35,mid(input,'bedroom')));if(input.requirements.wcs>=level)add(room('WC chung','wc',level,W-1.8,D*.55,1.8,2.3,mid(input,'wc')));if(level===input.plot.floors&&input.requirements.worship)add(room('Phòng thờ','worship',level,0,D*.43,W*.5,2.6,mid(input,'worship')));if(input.requirements.laundry&&level===input.plot.floors)add(room('Giặt phơi / logia','laundry',level,W*.5,D*.75,W*.5,D*.22,mid(input,'laundry')));if(input.requirements.balcony)add(room('Ban công','balcony',level,0,0,W,1.1,mid(input,'balcony')))}return{level,rooms};}
function cspSeed(input:DesignInput){const names=['Garage','Lounge Area','Kitchen'];if(input.requirements.masterSuite)names.push('Master Bedroom (with bathroom)');if(input.requirements.wcs)names.push('Bathroom');if(input.requirements.balcony)names.push('Balcony');return generateCspOrders(names,undefined,50)}
export function generateLayouts(input:DesignInput,count=8):Layout[]{const layouts:Layout[]=[];const orders=cspSeed(input);for(let v=0;v<count;v++){const order=orders[v%Math.max(1,orders.length)]||[];const floors=Array.from({length:input.plot.floors},(_,i)=>generateFloor(input,i+1,v));const layout:Layout={id:uid('layout'),name:`Phương án ${v+1}${order.length?' · CSP '+order.join(' → '):''}`,input:structuredClone(input),floors,issues:[],score:{total:0,areaFit:0,circulation:0,adjacency:0,light:0,technical:0,explanations:[]},createdAt:new Date().toISOString()};layout.issues=validateLayout(layout,input);layout.score=scoreLayout(layout);layouts.push(layout)}return layouts.sort((a,b)=>b.score.total-a.score.total)}
